### ISSUE TITLE
Block scalars not parsed correctly if last entry in file

### ISSUE THREAD

**Issue by charleskorn** [kareez/dahgan#31]
This is parsed successfully (based on [this file](https://github.com/kareez/dahgan/blob/develop/core/src/test/resources/io/dahgan/sample/l-yaml-stream.invoice.input)):

```yaml
lines: |
    458 Walkman Dr.
    Suite #292
city: Royal Oak
```

However, this fails with the address lines ("458 Walkman...") being marked as unparsed and no error token:

```yaml
lines: |
    458 Walkman Dr.
    Suite #292
```

It doesn't seem to matter what comes after the content - it can be anything as simple as a comment.

Both literal block scalars (`|`) and folded block scalars (`>`) seem to behave in the same way.

**Comment by kareez** [comment]
Can't reproduce this issue.  Could you please double check the indentations and verify if issue still exists?

**Comment by charleskorn** [comment]
I no longer have the reproduction for this as I've since switched to using another library sorry.

I'll close this issue.
