### ISSUE TITLE
Trailing Document Ignored

### ISSUE THREAD

**Issue by commonsguy** [kareez/dahgan#32]
Environment:
- `implementation 'com.github.mhshams:dahgan-loader:0.6.0'`
- Kotlin/JVM 1.3.31

I expect this is akin to #31.

`load()` returns a `LinkedHashMap` of the first document and ignores the second document for the following YAML:

```
title: Hello, World!
tags:
    - foo
    - bar
    - goo
--- |
This should be some **Markdown**!

This should also be in there
```

The same result occurs for:

```
title: Hello, World!
tags:
    - foo
    - bar
    - goo
---
This should be some **Markdown**!

This should also be in there
```

and:

```
---
title: Hello, World!
tags:
    - foo
    - bar
    - goo
---
This should be some **Markdown**!

This should also be in there
```

For each, I would expect `list()` to return a two-item `List`, with a `Map` for the first entry and a `String` for the second. In particular, I'm trying to set up a Jekyll-style YAML-plus-Markdown structure, so I'm aiming to keep whitespace intact for the `String` (hence the `--- |` in the first snippet).

Let me know if you need additional details &mdash; thanks!

**Comment by mhshams** [comment]
@commonsguy  there are two variations of load function in the public API. `load` and `loadAll`. the first one (`load`) assumes that your input has only __one__ yaml document. the second one (`loadAll`)  loads all available documents in the input stream or file or ....  I've checked your samples with `loadAll` and all of them seem fine.

**Comment by commonsguy** [comment]
My sincere apologies! I misread the example and was using `load()`.
